name: Indexing Hammer Bot
on:
  schedule:
    - cron: '0 * * * *' # سيعمل تلقائياً كل ساعة
  workflow_dispatch: # يتيح لك تشغيله يدوياً بضغطة زر للتجربة

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Libraries
        run: npm install googleapis firebase-admin axios
      - name: Execute Hammer
        env:
          GOOGLE_KEY: ${{ secrets.GOOGLE_KEY }}
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
        run: node index.js
