name: Manual Sitemap Generator
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Firebase Admin
        run: npm install firebase-admin

      - name: Run Generator Script
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
        run: node sitemap-generator.js

      # --- الخطوة السحرية: رفع الملف للسيرفر تلقائياً ---
      - name: FTP Deploy Sitemap
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public/  # المجلد الذي يحتوي على السايت ماب
          server-dir: ./public_html/public/ # المسار داخل سيرفرك (تأكد منه)
