name: Generate Sitemap
on:
  push:
    branches: [ main ]
  workflow_dispatch: # <-- Ù‡Ø°Ø§ Ù‡Ùˆ Ø§Ù„Ø³Ø·Ø± Ø§Ù„Ø³Ø­Ø±ÙŠ Ø§Ù„Ø°ÙŠ ÙŠØ¸Ù‡Ø± Ø§Ù„Ø²Ø± Ø§Ù„ÙŠØ¯ÙˆÙŠÙŠØ¹Ù…Ù„ Ø¹Ù†Ø¯ ÙƒÙ„ Ø±ÙØ¹ Ù„Ù„ÙƒÙˆØ¯

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install DB Admin
        run: npm install firebase-admin
      - name: Run Generator
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
        run: node sitemap-generator.js
      - name: Save to Repository
        run: |
          git config --local user.name 'Sitemap Bot'
          git config --local user.email 'bot@funclickergame.com'
          git add public/sitemap.xml
          git commit -m "ðŸ¤– Auto-update sitemap" || echo "No changes"
          git push
