name: Generate Sitemap
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Firebase Admin
        run: npm install firebase-admin

      - name: Run Generator Script
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
        run: node sitemap-generator.js

      - name: Save Sitemap to GitHub
        run: |
          git config --local user.name 'Sitemap Bot'
          git config --local user.email 'bot@funclickergame.com'
          git add public/sitemap.xml
          git commit -m "ðŸ¤– ØªØ­Ø¯ÙŠØ« Ø®Ø±ÙŠØ·Ø© Ø§Ù„Ù…ÙˆÙ‚Ø¹ ØªÙ„Ù‚Ø§Ø¦ÙŠØ§Ù‹" || echo "No changes"
          git push
